name: Docker Image CI - service-gateway

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image service-gateway
      run: docker build ./service-gateway/ --file Dockerfile --tag my-image-name:$(date +%s)

