name: Docker Image CI - microservices

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build microservices Docker images
      uses: actions/checkout@v2
      
    - name: Build docker image service-gateway 
      run: docker build service-gateway --file service-gateway/Dockerfile --tag service-gateway:$(date +%s)
      
    - name: Build docker image service-registration-discovery 
      run: docker build service-registration-discovery --file service-registration-discovery/Dockerfile --tag service-registration-discovery:$(date +%s)

    - name: Build docker image service-auth 
      run: docker build service-auth --file service-auth/Dockerfile --tag service-auth:$(date +%s)

    - name: Build docker image service-user 
      run: docker build service-user --file service-user/Dockerfile --tag service-user:$(date +%s)
