name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image service-registration-discovery
      run: docker build ./service-registration-discovery --file Dockerfile --tag my-image-name:$(date +%s)
      
    - uses: actions/checkout@v2
    - name: Build the Docker image service-gateway
      run: docker build ./service-gateway --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v2
    - name: Build the Docker image service-user
      run: docker build ./service-user --file Dockerfile --tag my-image-name:$(date +%s)

